# Generated by Django 4.2 on 2023-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tap_Recorder", "0002_tapes_delete_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapes",
            name="artist",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="tapes",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
