# Generated by Django 4.2 on 2023-05-02 19:07

import Tap_Recorder.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tap_Recorder", "0003_alter_tapes_artist_alter_tapes_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapes",
            name="album",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="tapes",
            name="singer",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="tapes",
            name="artist",
            field=models.CharField(default="unknown", max_length=25),
        ),
        migrations.AlterField(
            model_name="tapes",
            name="record_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=Tap_Recorder.models.custom_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3"]
                    )
                ],
            ),
        ),
    ]
