# Generated by Django 4.2 on 2023-05-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tap_Recorder", "0004_tapes_album_tapes_singer_alter_tapes_artist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tapes",
            name="artist",
        ),
        migrations.AddField(
            model_name="tapes",
            name="music_by",
            field=models.CharField(default="artist", max_length=25),
        ),
        migrations.AlterField(
            model_name="tapes",
            name="singer",
            field=models.CharField(default="artist", max_length=20),
        ),
    ]
